spring:
  application:
    name: dubbo-user
dubbo:
  enabled: true
  application:
    name: dubbo-user
  registry:
    address: zookeeper://192.168.21.128:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
    basePackages: dubbo.user.service.impl






